[package]
name = "image2slippytiles"
version = "1.1.0"
edition = "2021"
license-file = "LICENSE-LGPL"
description = "This program generates image tiles in the slippytile format (compatible with leaflet.js) from giant images and slide scan images such as SVS and DCM."
homepage = "https://github.com/coldfrontlabs/image2slippytiles"
repository =  "https://github.com/coldfrontlabs/image2slippytiles"
readme = "README.md"
categories = ["command-line-utilities", "multimedia::images", "science", "science::bioinformatics", "science::geo"]
keywords = ["images", "slippytiles", "tiles", "openslide", "map", "leaflet"]

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
fast_image_resize = "5.3.0"
hex_color = "3.0.0"
image = "0.25.8"
openslide-rs = "2.4.0"
openslide-sys = "1.0.8"
peak_alloc = "0.3.0"
serde = {version="1.0.218", features=["derive"] }
serde_json = "1.0.145"

[package.metadata.appimage]
auto_link = true

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
lto = true